name: build and push to s3
on: push
    # branches:
    # - main
    # pull_request:
    # types: [closed]


jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@2

      - name: setup node
        uses: actions/setup-node@1
        with:
          node-version: '12.x'

      - name: install
        run: npm ci

      - name: build
        run: npm run build

      - name: pwd
        run: pwd && ls
